### ISSUE TITLE
Update Styles

### ISSUE THREAD

**Issue by jajunk** [AcreetionOS-Linux/brochure-site#21]
## Site Builder Code

The existing site has very little style applied even though the `css` and `scss` are full of lines of code. Much of it is not doing anything. Including all of the `scss`. 

## ToDo

- [ ] Pull out what is important and junk the rest. 
- [ ] Add the styles from Cryptid. 
- [ ] Decide if she is going to become a part of the project.
